import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "../utils/api";
import FeaturedDecks from "../components/FeaturedDecks";
const Home: NextPage = () => {

  // const {data, isLoading} = api.example.getAll.useQuery();
  
  return (
    <>
      <Head>
        <title>One Piece Deck Builder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full w-full flex flex-col justify-center max-w-[1080px] items-center">
        <section className="flex flex-wrap items-center mx-auto gap-8">
          <div className="flex flex-col gap-4 items-center justify-center w-full">
            <h1 className='text-5xl tracking-wide font-bold text-center'>Welcome to Haki Builder</h1>
            <p className="text-lg text-gray-400">Your number one site for One Piece TCG Deck Building</p>
          </div>
          <Image
            src='/images/heroImage.png'
            alt='Hero Image'
            width={430}
            height={100}
            className='rounded-lg mx-auto'
          />
        </section>
        <section className="w-full flex flex-col justify-center px-4">
          <h3 className="text-2xl my-4">Popular Decks</h3>
          <FeaturedDecks />
        </section>
      </div>
    </>
  );
};
{/* <Link href={'/deckbuilder'}>Deck Builder</Link> */}

export default Home;



/*
light color scheme
bg-gray-200 for bg
*/